---
title: "Probabilidad de Suicidios en el Mundo   "
author: "Christopher Weber"

output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

  
    
      
      
# Introducción

Actualmente con el avance de la economía mundial, muchas personas han visto aumentados sus niveles de estrés, debido a preocupaciones y exigencias del medio. Estas últimas, se evidencian en los empleos, ya que, al estar inmersos en un sistema mayormente capitalista a nivel mundial, las empresas dejan en claro que, al no cumplir con las exigencias, pueden cambiar al personal rápidamente y sin repercusiones. Es justamente esto, lo que podría estar influyendo en la salud mental de la población mundial, viendo una correlación con la tasa de suicidio en cada país.  

Esta temática no ha sido de gran relevancia en los últimos años, dado que no se ha otorgado la importancia necesaria como para relacionarlo con causas puntuales que afecten el aumento, sino que se considera como una muerte más dentro de la sociedad. Sin embargo, gracias a los aportes del ámbito psicológico y psiquiátrico se ha podido dilucidar que existirían causas probables para este fenómeno.  

Es por esto, que el presente trabajo busca comparar las características de los países con más altos y bajos promedios de suicidio, para lo cual se utilizan los datos provenientes del proyecto gapminder, que considera el número de suicidios por año en distintos países del mundo, tomando en cuenta las cifras de 1990 al año 2016.Basándonos en estos datos se identifican los países con mayor y menor promedio a lo largo de su historia. Este proceso se repite a nivel de continente y damos una breve descripción de cada uno. Una vez identificados los países, se analizan las características principales de cada uno, para identificar la posible correlación de estos con los promedios de suicidio.

# Datos  

La base de datos que ocuparemos originalmente tiene una dimensión de 187x27. Donde la primera columna son los nombres de cada país y las columnas que quedan indican primero el año y segundo la cantidad de suicidios que ocurrieron en cada país. Al tener tal cantidad de datos se necesitó una cifra representativa de cada país, por lo que se calcula el promedio de suicidios a lo largo de los años. A continuación, se extrae el máximo y mínimo de estos promedios y se archivan. Posteriormente agrupamos a los países por continente y se vuelve a calcular el máximo y mínimo y archivan los datos. Finalmente, cada dato que archivamos se divide por la cantidad de habitantes en cada país, lo que llamaremos "la probabilidad de que alguien se suicide en dicho país".   

\newpage



# Resultado

Los primeros resultados revelaron que India y Antigua y Barbuda son los países con mayor y menor promedio de suicidios a lo largo de los años. A continuación, se describen brevemente algunas características de estos.    

India es el país con mayor promedio de suicidios a lo largo de los años. Algunos factores que pueden influenciar en esto, es que es el país más poblado del mundo con $1.353$ miles de millones de habitantes y tiene un alto nivel de pobreza. Por otro lado, económicamente su fuerte es la agricultura y la manufactura. La gran cantidad de población y la importante brecha social podría indicar que las condiciones no son óptimas para una buena calidad de vida, lo que podría llevar al elevado promedio de suicidios. La probabilidad de que alguien se suicide en India es de 14.95 %.  
  
Por otro lado, Antigua y Barbuda es un país ubicado en el centro de América. Su población es mucho menor que India, siendo $92.436$ habitantes en 2015.Su economía se basa principalmente en el turismo y la agricultura. Al tener menor cantidad de habitantes, menor brecha de desigualdad y mayor estabilidad económica es posible considerar que exista un menor número de suicidios, lo que podría indicar que existen mejores condiciones para vivir. En base a su población el porcentaje de suicidios por año es 1.8%.  


A continuación, se analizan los países con mayor y menor promedio de suicidios por cada continente.     


Considerando el continente de América completo (norte, centro y sur), Antigua y Barbuda sigue siendo el país con menor promedio de suicidios según lo visto anteriormente. Por el contrario, el país con mayor promedio de suicidios por año es Estados Unidos. El país cuenta con una economía estable y salud accesible y de calidad. Sin embargo, las brechas sociales son muy marcadas. Su población es de $320$ millones hasta el año 2015. Pese a las favorables características, la alta exigencia de sus trabajos podría influenciar en la probabilidad de suicidios por año que alcanza un 12.16 %.    

| Países  | Antigua y Barbuda | USA |
| ---------- | ---------- | ---------- |
| Probabilidad | 1.8%  |  12.16% |  

En cuanto a Europa, el país con menos suicidios por año es Andorra, donde existe una población $77.011$ hasta el 2015. En sus comienzos era un país muy pobre y excluido, pero con los años se fue consolidando y posee un estado democrático.  Su porcentaje de suicidios es 8.86%. Por otro lado, el país con mayor promedio de suicidios en Europa es Rusia que tiene una población de $144,1$ millones. Este país se reconoce como una potencia mundial, con una economía estable, un sistema de salud eficiente y educación de calidad. Pese a lo anterior, su porcentaje de suicido es 4.3 %.    

| Países  | Andorra | Rusia |
| ---------- | ---------- | ---------- |
| Probabilidad  | 8.86%  |  4.3% |  

Con relación a Oceanía, el país con menor promedio de suicidios por año es Tonga que tiene una población de $103.197$ habitantes. Su gobierno consta de una Monarquía constitucional. Su económica se ve limitada por los recursos naturales que posee y las pequeñas zonas de comercio, pero lo que lo hace más inestable es la cantidad de catástrofes naturales. su porcentaje de suicidios por año es 6.56%. En cambio, Australia es el país con mayor promedio de suicidios por año. Cuenta con una población de $24,82$ millones y , al contrario de Tonga , ellos poseen una economía muy estable y en crecimiento. su sistema educativo es uno de los más reconocidos del mundo. A pesar de tener mejores condiciones para las personas, presenta un porcentaje de suicidios es 10.29%.   

| Países  | Tonga | Australia |
| ---------- | ---------- | ---------- |
| Probabilidad  | 6.56%  |  10.29% |  


En el caso del continente africano, el país con menor promedio de suicidios es Santo Tomé y Príncipe, cuya población es de $211.028$ habitantes. Principalmente su economía se basa en la agricultura y la pesca. Es un país con mucha pobreza; se calcula que más de la mitad de la población vive por debajo del umbral de pobreza, y que el 29% vive en estado de extrema pobreza. Los bajos salarios, así como la falta de oportunidades laborales hacen más difíciles sus condiciones de vida. su promedio de suicidios es 1.23%. Por otra parte, Sudáfrica es un país con un alto nivel de pobreza y una gran brecha entre pobres y ricos, pero dentro de África es el que tiene el mejor sistema económico y estabilidad. Aun así, su crecimiento con respecto a otros países del mundo es lento. Su porcentaje de suicidios es de 13.15%.   


| Países  | Santo Tomé y Príncipe | South África |
| ---------- | ---------- | ---------- |
| Probabilidad  | 1.23%  |  13.15% |  

Por último, en el continente asiático, Maldivas es un país con una población de $454.915$. Un gran porcentaje de la población vive bajo la línea de pobreza, lo que significa que la gente no logra cubrir sus necesidades básicas. Su mayor ingreso económico es la pesca, ya que tienen pocos terrenos para desarrollar la agricultura. El turismo es otra fuente de ingresos, lo que los vuelve dependientes de las condiciones climáticas para obtener sus productos. A pesar de esto tiene una economía muy estable. El porcentaje de suicidios es  2.58%. En cuanto al país con mayor promedio nos referimos a India, el cual analizamos anteriormente.

| Países  | Maldivas | India |
| ---------- | ---------- | ---------- |
| Probabilidad  |2.58%  |  14.95% |  




Los resultados obtenidos anteriormente se resumen en las siguientes tablas.  


### Países con menor promedio de suicidios de cada continente

| Países  | Antigua y Barbuda | Maldivas | Santo Tomé y Príncipe | Tonga|Andorra | 
| ---------- | ---------- | ---------- |---------- |---------- |---------- |
| Probabilidad  | 1.8%  |  2.58% | 1.23% | 6.56|8.86% |   


### Países con mayor promedio de suicidios de cada continente

| Países  | USA | India |South África | Australia| Rusia| 
| ---------- | ---------- | ---------- |---------- |---------- |---------- |
| Probabilidad  | 12.16%  |  14.95% | 13.15% |10.29% | 4.3%|  


\newpage


# Conclusión

Comúnmente se relaciona la estabilidad económica, acceso a salud, calidad de educación y empleabilidad por una mayor calidad de vida y por ende una menor cantidad de suicidios. Sin embargo, se pudo evidenciar que los países que cuentan con un menor promedio de suicidios mayoritariamente eran países tercermundistas con falencias en los ámbitos antes mencionados, como es el caso de Antigua y Barbuda, Maldivas, Santo Tomé y Príncipe y Tonga, donde dependen del turismo y extracción de recursos principalmente.  

Por otro lado, considerando el desarrollo económico, la calidad de vida y la estabilidad país se esperaría que el promedio de suicidios sea bajo. Sin embargo, encontramos a grandes potencias como USA, Australia y Rusia dentro del grupo de países con mayor cantidad de suicidios anuales, lo que se podría explicar por una alta exigencia laboral y alto nivel de estrés que esto conlleva, afectando gravemente a la salud mental de las personas.  


también podemos evidenciar que, al dividir la cantidad de suicidios por la cantidad de habitantes para obtener la probabilidad de suicidios en cada país, en algunos casos el porcentaje era menor en países con mayor promedio que los que tienen menor promedio, como es el caso de Rusia.

Finalmente queda claro que no se pueden establecer relaciones directas entre los factores sociales y económicos de cada país con la cantidad de suicidios probables. Es necesario situarse en cada contexto para comprender el fenómeno en su totalidad, dado que sólo con estos registros no se pueden obtener datos concluyentes. 


