---
title: "Informe - Introduccion - Resultados "
author: "Christopher Weber"

output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Hoy en día, como avanza el mundo, el nivel de estrés y preocupaciones que tiene la gente es muy grande. El hecho de que en un trabajo seamos desechados si no cumplimos, pone mucha presión en la gente y esto se puede reflejar en el número de suicidios por cada país.  
  
Quizás es un tema que en los últimos 20 años no había tomado mayor importancia, pero hoy trataremos de identificar las posibles explicaciones de la gran cantidad de suicidios en distintos países, para lo cual sacamos una base de datos de gapminder de el número de suicidios por año de distintos países del mundo, los cuales van desde 1990 hasta el año 2016.  
  
Los suicidios hace algunos años eran considera una muerte más solamente, pero como ahora el campo psicológico y psiquiátrico ha avanzado tanto, se le ha otorgado más importancia.  
  
 En este trabajo analizaremos si influye el lugar de nacimiento (país) en la probabilidad de suicidio, también identificaremos las características de estos países (donde los suicidios se presentan en mayor número), para poder conocer los factores influyentes en este acto e influir en su disminución.  
    
El primer objetivo es identificar el país que cuenta con mayor cantidad de suicidios en promedio Da lo largo su historia, luego de esto separamos los países por continente y damos una breve descripción de cada uno. El objetivo es conocer cuáles son los países con la mayor y menor tasa de suicidio por continente. Para esto, se analiza el promedio anual de suicidio en un periodo de 26 años. Una vez identificados los países, se analizan los factores económicos(como la jornada laboral ,tipo de economía)y sociales (dictadura , democracia) en los cuales se encuentra el país y continente, para ver influencia de estos en la tasa de suicidio.


--------------------------------------------------------------------------------------------------------------------------------------------------------------


Resultados 

Nuestros primeros resultados revelaron que India y Antigua and Barbuda son los países con mayor y menor promedio de suicidios a lo largo de los años a continuación describiremos brevemente algunas características de estos , India es el país con mayor promedio de suicidios a lo largo de los años , factores que pueden influenciar en esto es que es el país más poblado del mundo  con $1.353$ miles de millones y tiene un alto nivel de pobreza por otro lado  económicamente su fuerte es la agricultura y la manufactura , la gran cantidad de población y la importante brecha social podría indicar que las condiciones no son óptimas lo que podría llevar a tal promedio de suicidios la  probabilidad de que alguien muera en India es de $ 14.95 % $% Por otro lado Antigua y Barbuda es un país ubicado en el centro de América su población es mucho menor que india , siendo $92.436$ habitantes en 2015 y su economía se basa en el turismo y la agricultura , al tener mucho menos población y una menor brecha de desigualdad y una estabilidad económica hacen considerar que tengan una número menor de suicidios porque esto nos puede indicar que tienen condiciones mejores para vivir ,en base a su población el porcentaje que alguien se suicide por año es  $1.8%$%.


Ahora analizaremos los países con mayor y menor promedio de suicidios por cada continente   


Cuando hablemos de América nos referiremos tanto a la parte norte como del sur, en este caso ya conocemos el país con menos suicidios que es Antigua and Barbuda
y ya observamos alguna de sus características anteriormente, por otro lado el país con mayor promedio de suicidios por año es Estados unidos, sabemos la excelente economía que ellos tienen y que es  muy estable, por otro lado las brechas sociales son muy marcadas  , su población se dispara a $320$ millones hasta el 2015 , nos damos cuenta que una estabilidad económica no indica el hecho de una menor tasa de suicidios . su porcentaje de suicidios por año es $12.16 % $%.  

Ahora hablaremos de Europa el país con menos suicidios por año es Andorra que es un país que tiene una población $77.011$ hasta el 2015, en sus comienzo era un país muy pobre y excluido pero con los años se fue consolidando sólidamente , y un estado democrático  su porcentaje  de muertes  $8.86$%,por otro lado el país con mayor suicidios en Europa es rusia que tiene una población $144,1$ millones sabemos que rusia es una potencia mundial con una buena economía y bien establecido y su porcentaje  de suicido es  $4.3$ %.  

Mientras Oceanía por su parte el país con menor promedio de suicidios por año es Tonga que tiene una población de $103.197$, su gobierno consta de una Monarquía constitucional ,su estabilidad económica se ve limitada por los recursos naturales que posee y pequeña zona de comercio pero lo que la lo hace más inestable es la cantidad de catástrofes naturales lo que lo hace muy inestable su porcentaje de suicidios por año es $6.56$%,en cambio Australia es que mayor promedio de muertes tiene por año , tiene una población de $24,82$  millones, al contrario de Tonga , ellos poseen una economía muy estable y siempre creciendo , su sistema educativo es uno de los más reconocidos del mundo , también algo  que es importante 1/3 de este país es desértico pero lo compensa con su gran diversidad de fauna  su porcentaje de suicidios  es $10.2889$%.  

A su vez el continente africano, que por su lado el país con menor promedio de suicidios es Santo Tomé y Príncipe, con una población de $211.028$ principalmente su economía se basa en la agricultura y la pesca es un país con mucha pobreza, se calcula que más de la mitad de la población vive por debajo del umbral de pobreza, y que el 29% vive en estado de extrema pobreza. Los bajos salarios, así como la falta de oportunidades laborales hacen más difíciles sus condiciones de vida. su promedio de suicidios $1.23$%, por otra parte South África es un país con un alto nivel de pobreza y una gran brecha entre pobres y ricos, pero dentro de áfrica es el que tiene el mejor sistema económico mucho más estable, con crecimiento lento pero muy estable, porcentaje $13.15$%. 

Por ultimo en Asia Maldivas es un país con una población de $454.915$ un gran porcentaje de la población vive bajo la línea de pobreza por esta gente no tiene ni siquiera para comer , su economía es su mayor ingreso es por la pesca, ya que tienen pocos terrenos para desarrollar la agricultura y el turismo es su otra fuente de ingresos , esto los hace muy dependientes a pesar de esto tiene una economía muy estable , porcentaje de suicidios es  $2.58$% y ya hablamos del país con mayor promedio que era India.


--------------------------------------------------------------------------------------------------------------------------------------------------------------------


Tengo pensado poner una Tabla que sintetise los numeros antes dichos comparando  todos los paises con menor promedio y todos los de mayor y ver el porcentaje suicidios comparado con su poblacion y concluir no se que grafico podria servirme para representar algo por eso no puse nada sigo pensando 










